"""reply and forward

Revision ID: 54f9bd686ffb
Revises: b1c2d3e4f5a6
Create Date: 2026-07-15 11:17:44.117876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f9bd686ffb'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_chat_message', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.add_column('general_chat_message', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'general_chat_message', 'reply', ['reply_id'], ['id'])
    op.create_foreign_key(None, 'general_chat_message', 'general_chat_message', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'general_chat_message', type_='foreignkey')
    op.drop_constraint(None, 'general_chat_message', type_='foreignkey')
    op.drop_column('general_chat_message', 'parent_id')
    op.drop_column('general_chat_message', 'reply_id')
    # ### end Alembic commands ###
