"""add user name to ticet

Revision ID: c0fc69a9a7e2
Revises: 1ca7148f255f
Create Date: 2026-07-09 15:09:09.099827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fc69a9a7e2'
down_revision: Union[str, Sequence[str], None] = '1ca7148f255f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('soc_user_name', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'soc_user_name')
    # ### end Alembic commands ###
