"""add push for pwa

Revision ID: 47ee1c377c36
Revises: a1b2c3d4e5f6
Create Date: 2026-07-22 11:16:38.839623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47ee1c377c36'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscription_user_id'), 'push_subscription', ['user_id'], unique=False)
    op.alter_column('attachment', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('attachment', 'content_type',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('attachment_ibfk_1'), 'attachment', type_='foreignkey')
    op.drop_constraint(op.f('attachment_ibfk_2'), 'attachment', type_='foreignkey')
    op.drop_constraint(op.f('attachment_ibfk_3'), 'attachment', type_='foreignkey')
    op.create_foreign_key(None, 'attachment', 'ticket', ['ticket_id'], ['id'])
    op.create_foreign_key(None, 'attachment', 'general_chat_message', ['general_chat_message_id'], ['id'])
    op.create_foreign_key(None, 'attachment', 'reply', ['reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.create_foreign_key(op.f('attachment_ibfk_3'), 'attachment', 'ticket', ['ticket_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('attachment_ibfk_2'), 'attachment', 'reply', ['reply_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('attachment_ibfk_1'), 'attachment', 'general_chat_message', ['general_chat_message_id'], ['id'], ondelete='SET NULL')
    op.alter_column('attachment', 'content_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('attachment', 'file_path',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_index(op.f('ix_push_subscription_user_id'), table_name='push_subscription')
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
