"""Add assigned_to_id to ticket

Revision ID: a7e543e9a78f
Revises: a363b1d4e3aa
Create Date: 2026-07-10 15:33:51.073526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e543e9a78f'
down_revision: Union[str, Sequence[str], None] = 'a363b1d4e3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'user', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'assigned_to_id')
    # ### end Alembic commands ###
