"""add tg_message_id and reply_to_reply_id

Revision ID: ab12cd34ef56
Revises: cd00fbc7247d
Create Date: 2026-07-17 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab12cd34ef56'
down_revision: Union[str, Sequence[str], None] = 'cd00fbc7247d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('tg_message_id', sa.BigInteger(), nullable=True))
    op.add_column('reply', sa.Column('tg_message_id', sa.BigInteger(), nullable=True))
    op.add_column('reply', sa.Column('reply_to_reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reply', 'reply', ['reply_to_reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_column('reply', 'reply_to_reply_id')
    op.drop_column('reply', 'tg_message_id')
    op.drop_column('ticket', 'tg_message_id')
    # ### end Alembic commands ###
